<?php
$_config['db_connect']="mysql:host=localhost;dbname=ENTER-DB-NAME";
$_config['db_user']="ENTER-DB-USER";
$_config['db_pass']="ENTER-DB-PASS";
$_config['max_peers']=30;
$_config['testnet']=false;
$_config['coin']="arionum";
$_config['peer_max_mempool']=100;
$_config['max_mempool_rebroadcast']=5000;
$_config['sanity_rebroadcast_height']=30;
$_config['transaction_propagation_peers']=5;
$_config['max_test_peers']=5;
$_config['sanity_recheck_blocks']=10;
$_config['public_api']=true;
$_config['allowed_hosts']=array("127.0.0.1");
$_config['sanity_interval']=900;
?>
